package app

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"codingto/internal/applog"
	"codingto/internal/piagent"
)

const (
	chatgptOAuthKey          = "openai-codex"
	chatgptCodexBaseURL      = "https://chatgpt.com/backend-api"
	chatgptFlowTimeout       = 5 * time.Minute
	chatgptAuthMigrationFile = "chatgpt-shared-auth-v1.migrated"
	// chatgptSharedAgentID labels the shared ChatGPT credential in API payloads.
	// It no longer refers to a specific agent because every CodingTo runtime
	// reads the credential from Pi's default auth.json.
	chatgptSharedAgentID = "default"
)

// ChatGPTAccount is non-secret subscription metadata for the shared ChatGPT
// credential stored in Pi's default agent directory.
type ChatGPTAccount struct {
	// AgentID is a fixed label ("default") indicating the shared credential.
	AgentID string `json:"agentId"`
	// LoggedIn reports whether a usable OAuth credential entry exists.
	LoggedIn bool `json:"loggedIn"`
	// AccountID is the ChatGPT account id declared in the OAuth credential.
	AccountID string `json:"accountId,omitempty"`
	// Expires is the access-token expiry in Unix milliseconds. Pi refreshes an
	// expired access token from the refresh token when the Agent makes a request.
	Expires int64 `json:"expires,omitempty"`
}

// ChatGPTLoginState describes the shared ChatGPT login flow.
type ChatGPTLoginState struct {
	// AgentID is a fixed label ("default") indicating the shared credential.
	AgentID string `json:"agentId,omitempty"`
	// Status is idle, pending, completed, error, or cancelled.
	Status string `json:"status"`
	// AuthURL is generated by Pi/pi-ai and opened by the frontend.
	AuthURL string `json:"authUrl,omitempty"`
	// AccountID and Expires are non-secret completion metadata.
	AccountID string `json:"accountId,omitempty"`
	Expires   int64  `json:"expires,omitempty"`
	// Error is a user-readable error that never contains tokens or raw responses.
	Error string `json:"error,omitempty"`
}

type chatgptOAuthCredential struct {
	Type      string `json:"type"`
	Access    string `json:"access"`
	Refresh   string `json:"refresh"`
	Expires   int64  `json:"expires"`
	AccountID string `json:"accountId"`
}

type chatgptFlow struct {
	cancel context.CancelFunc
	ready  chan struct{}
	done   chan struct{}

	mu        sync.Mutex
	authURL   string
	result    ChatGPTLoginState
	readyOnce sync.Once
	doneOnce  sync.Once
}

func (f *chatgptFlow) setAuthURL(authURL string) {
	f.mu.Lock()
	f.authURL = authURL
	f.mu.Unlock()
	f.readyOnce.Do(func() { close(f.ready) })
}

func (f *chatgptFlow) finish(result ChatGPTLoginState) {
	f.doneOnce.Do(func() {
		f.mu.Lock()
		f.result = result
		f.mu.Unlock()
		f.readyOnce.Do(func() { close(f.ready) })
		close(f.done)
	})
}

func (f *chatgptFlow) snapshot() (string, ChatGPTLoginState) {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.authURL, f.result
}

// ChatGPTLoginStart starts Pi's built-in OpenAI Codex OAuth flow. The
// credential is written into Pi's default agent directory (~/.pi/agent).
// CodingTo's SDK RPC launcher gives every isolated Agent the same authPath, so
// Pi serializes refresh-token rotation against this one shared credential.
func (a *App) ChatGPTLoginStart() (ChatGPTLoginState, error) {
	// The credential is installed into Pi's default agent directory. Every
	// CodingTo runtime receives this exact authPath while retaining its own
	// resource and model directory.
	defaultDir, err := piagent.DefaultAgentDir()
	if err != nil {
		applog.Errorf("resolve default Pi agent dir for ChatGPT login: %v", err)
		return ChatGPTLoginState{}, errors.New("无法确定 Pi 默认 Agent 目录，请稍后重试")
	}
	if err := os.MkdirAll(defaultDir, 0o700); err != nil {
		applog.Errorf("create default Pi agent directory for ChatGPT login: %v", err)
		return ChatGPTLoginState{}, errors.New("无法准备 Pi 默认 Agent 目录，请稍后重试")
	}

	a.chatgptMu.Lock()
	if a.chatgptFlow != nil {
		select {
		case <-a.chatgptFlow.done:
			// A terminal result that the frontend stopped polling must not block
			// every later login attempt. ChatGPTLoginStatus still consumes the
			// result normally when it is called before a new start.
			a.chatgptFlow = nil
		default:
			a.chatgptMu.Unlock()
			return ChatGPTLoginState{}, errors.New("已有一个 ChatGPT 登录流程正在进行，请等待完成或先取消")
		}
	}
	ctx, cancel := context.WithTimeout(context.Background(), chatgptFlowTimeout)
	flow := &chatgptFlow{
		cancel: cancel,
		ready:  make(chan struct{}),
		done:   make(chan struct{}),
	}
	a.chatgptFlow = flow
	a.chatgptMu.Unlock()

	go a.runChatGPTLogin(ctx, flow, defaultDir)
	select {
	case <-flow.ready:
		authURL, result := flow.snapshot()
		if authURL != "" {
			return ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "pending", AuthURL: authURL}, nil
		}
		a.clearChatGPTFlow(flow)
		if result.Status == "" {
			result = ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "error", Error: "Pi 未返回登录地址，请重试"}
		}
		return result, nil
	case <-time.After(20 * time.Second):
		cancel()
		result := ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "error", Error: "启动 ChatGPT 登录超时，请重试"}
		flow.finish(result)
		a.clearChatGPTFlow(flow)
		return result, nil
	}
}

func (a *App) runChatGPTLogin(ctx context.Context, flow *chatgptFlow, dataDir string) {
	defer flow.cancel()
	var completed piagent.CodexAuthEvent
	err := piagent.RunOpenAICodexLogin(ctx, dataDir, func(event piagent.CodexAuthEvent) {
		switch event.Type {
		case "auth_url":
			flow.setAuthURL(event.URL)
		case "completed":
			completed = event
		}
	})
	if err != nil {
		applog.Errorf("Pi ChatGPT login failed: %v", err)
		status := "error"
		if errors.Is(err, context.Canceled) {
			status = "cancelled"
		}
		flow.finish(ChatGPTLoginState{
			AgentID: chatgptSharedAgentID,
			Status:  status,
			Error:   chatGPTLoginError(err),
		})
		return
	}
	// 所有 CodingTo Agent 的 ModelRuntime 均直接使用该默认目录中的同一个
	// auth.json；无需复制，刷新时由 Pi 的凭证文件锁串行更新。已运行的
	// ModelRuntime 会缓存凭证快照，因此空闲会话立即重启，忙碌会话在本轮
	// 结束后按现有 deferred-restart 机制重启。
	if a.agent != nil {
		if err := a.agent.Restart(); err != nil {
			applog.Warnf("refresh Agent runtimes after ChatGPT login: %v", err)
		}
	}
	applog.Infof("ChatGPT login completed")
	flow.finish(ChatGPTLoginState{
		AgentID:   chatgptSharedAgentID,
		Status:    "completed",
		AccountID: completed.AccountID,
		Expires:   completed.Expires,
	})
}

// ChatGPTLoginCancel cancels the active login flow. The shared credential
// flow is global, so no agent identifier is involved.
func (a *App) ChatGPTLoginCancel() error {
	a.chatgptMu.Lock()
	flow := a.chatgptFlow
	a.chatgptMu.Unlock()
	if flow == nil {
		return nil
	}
	flow.cancel()
	flow.finish(ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "cancelled", Error: "已取消登录"})
	a.clearChatGPTFlow(flow)
	return nil
}

// ChatGPTLoginStatus returns the active flow state. Completed results are
// consumed once so a later login can start immediately. The status reflects
// the shared ChatGPT credential in Pi's default directory.
func (a *App) ChatGPTLoginStatus() (ChatGPTLoginState, error) {
	a.chatgptMu.Lock()
	flow := a.chatgptFlow
	a.chatgptMu.Unlock()
	if flow == nil {
		account, err := a.chatGPTAccount()
		if err != nil {
			return ChatGPTLoginState{}, err
		}
		if account.LoggedIn {
			return ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "completed", AccountID: account.AccountID, Expires: account.Expires}, nil
		}
		return ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "idle"}, nil
	}
	select {
	case <-flow.done:
		_, result := flow.snapshot()
		a.clearChatGPTFlow(flow)
		return result, nil
	default:
		authURL, _ := flow.snapshot()
		return ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "pending", AuthURL: authURL}, nil
	}
}

// ChatGPTLogout removes the openai-codex credential from the one shared Pi
// auth.json used by every CodingTo Agent.
func (a *App) ChatGPTLogout() error {
	a.chatgptMu.Lock()
	flow := a.chatgptFlow
	a.chatgptMu.Unlock()
	if flow != nil {
		return errors.New("ChatGPT 登录流程正在进行，请先完成或取消登录")
	}
	defaultDir, err := piagent.DefaultAgentDir()
	if err != nil {
		applog.Errorf("resolve default Pi agent dir for ChatGPT logout: %v", err)
		return errors.New("无法确定 Pi 默认 Agent 目录，请稍后重试")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := piagent.RunOpenAICodexLogout(ctx, defaultDir); err != nil {
		applog.Errorf("Pi ChatGPT logout failed: %v", err)
		return errors.New("ChatGPT 登出失败，请稍后重试")
	}
	// 运行中的 Pi ModelRuntime 缓存有效 access token；重启（忙碌时延迟到
	// 当前轮结束）确保登出不会继续沿用缓存凭证。
	if a.agent != nil {
		if err := a.agent.Restart(); err != nil {
			applog.Warnf("refresh Agent runtimes after ChatGPT logout: %v", err)
		}
	}
	applog.Infof("ChatGPT logout completed")
	return nil
}

// ChatGPTAccount returns non-secret subscription status for the shared
// ChatGPT credential stored in Pi's default agent directory.
func (a *App) ChatGPTAccount() (ChatGPTAccount, error) {
	return a.chatGPTAccount()
}

// ChatGPTUsage returns the shared ChatGPT subscription quota without exposing
// OAuth credentials. Pi refreshes an expired access token before the request.
func (a *App) ChatGPTUsage() (ProviderUsage, error) {
	defaultDir, err := piagent.DefaultAgentDir()
	if err != nil {
		applog.Errorf("resolve default Pi agent dir for ChatGPT usage: %v", err)
		return ProviderUsage{}, errors.New("无法确定 Pi 默认 Agent 目录，请稍后重试")
	}
	if _, ok, err := readChatGPTAuthEntry(defaultDir); err != nil {
		applog.Errorf("read ChatGPT auth before usage request: %v", err)
		return ProviderUsage{}, errors.New("无法读取 ChatGPT 登录状态")
	} else if !ok {
		return ProviderUsage{}, errors.New("尚未登录 ChatGPT")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	usage, err := piagent.RunOpenAICodexUsage(ctx, defaultDir)
	if err != nil {
		applog.Errorf("query ChatGPT subscription usage: %v", err)
		return ProviderUsage{}, errors.New("无法查询 ChatGPT 使用额度，请稍后重试")
	}
	return ProviderUsage{
		PlanType: usage.PlanType,
		Rolling:  UsageWindow{Percent: usage.Rolling.Percent, ResetSeconds: usage.Rolling.ResetSeconds},
		Weekly:   UsageWindow{Percent: usage.Weekly.Percent, ResetSeconds: usage.Weekly.ResetSeconds},
	}, nil
}

func (a *App) chatGPTAccount() (ChatGPTAccount, error) {
	defaultDir, err := piagent.DefaultAgentDir()
	if err != nil {
		applog.Errorf("resolve default Pi agent dir for ChatGPT status: %v", err)
		return ChatGPTAccount{}, errors.New("无法确定 Pi 默认 Agent 目录，请稍后重试")
	}
	cred, ok, err := readChatGPTAuthEntry(defaultDir)
	if err != nil {
		applog.Errorf("read ChatGPT auth from default dir: %v", err)
		return ChatGPTAccount{}, errors.New("无法读取 ChatGPT 登录状态")
	}
	return ChatGPTAccount{
		AgentID:   chatgptSharedAgentID,
		LoggedIn:  ok,
		AccountID: cred.AccountID,
		Expires:   cred.Expires,
	}, nil
}

// ApplyCodexProvider ensures the global provider/model catalog contains the
// OpenAI Codex subscription provider. Credentials are stored once in Pi's
// default directory and shared by every CodingTo runtime through authPath.
func (a *App) ApplyCodexProvider() (AppConfig, error) {
	cfg := a.store.Get()
	for index := range cfg.Providers {
		if cfg.Providers[index].Name != chatgptOAuthKey {
			continue
		}
		// openai-codex is a Pi built-in provider, so its OAuth implementation
		// is inherited by provider id. models.json only accepts "radius" in
		// the oauth field; clear the value written by early development builds.
		if cfg.Providers[index].OAuth == chatgptOAuthKey {
			cfg.Providers[index].OAuth = ""
		}
		return a.SaveConfig(cfg)
	}
	cfg.Providers = append(cfg.Providers, piagent.Provider{
		Name:    chatgptOAuthKey,
		Label:   "ChatGPT (Codex)",
		Vendor:  chatgptOAuthKey,
		BaseURL: chatgptCodexBaseURL,
		Enabled: true,
		Models:  codexProviderModels(),
	})
	return a.SaveConfig(cfg)
}

func (a *App) clearChatGPTFlow(flow *chatgptFlow) {
	a.chatgptMu.Lock()
	if a.chatgptFlow == flow {
		a.chatgptFlow = nil
	}
	a.chatgptMu.Unlock()
}

func (a *App) cancelChatGPTFlow() {
	a.chatgptMu.Lock()
	flow := a.chatgptFlow
	a.chatgptFlow = nil
	a.chatgptMu.Unlock()
	if flow != nil {
		flow.cancel()
		flow.finish(ChatGPTLoginState{AgentID: chatgptSharedAgentID, Status: "cancelled", Error: "应用正在关闭"})
	}
}

func chatGPTLoginError(err error) string {
	switch {
	case errors.Is(err, context.DeadlineExceeded):
		return "登录超时，请重新发起"
	case errors.Is(err, context.Canceled):
		return "已取消登录"
	case strings.Contains(err.Error(), "sdk_unavailable"):
		return "当前 Pi 版本不支持此登录方式，请更新 Pi 后重试"
	case strings.Contains(err.Error(), "credential_store_failed"):
		return "登录凭证保存失败，请检查 Agent 数据目录权限后重试"
	case strings.Contains(err.Error(), "callback_failed"):
		return "登录回调未完成，请确认本机回调端口未被占用后重试"
	default:
		return "ChatGPT 登录失败，请重试"
	}
}

func readChatGPTAuthEntry(dataDir string) (chatgptOAuthCredential, bool, error) {
	var cred chatgptOAuthCredential
	data, err := os.ReadFile(filepath.Join(dataDir, "auth.json"))
	if err != nil {
		if os.IsNotExist(err) {
			return cred, false, nil
		}
		return cred, false, err
	}
	var entries map[string]json.RawMessage
	if err := json.Unmarshal(data, &entries); err != nil {
		return cred, false, err
	}
	raw, ok := entries[chatgptOAuthKey]
	if !ok {
		return cred, false, nil
	}
	if err := json.Unmarshal(raw, &cred); err != nil {
		return cred, false, err
	}
	if cred.Type != "oauth" || strings.TrimSpace(cred.Access) == "" || strings.TrimSpace(cred.Refresh) == "" {
		return cred, false, nil
	}
	return cred, true, nil
}

func isOpenAICodexProvider(providers []piagent.Provider, providerName string) bool {
	for _, provider := range providers {
		if provider.Name != providerName {
			continue
		}
		if provider.Vendor == chatgptOAuthKey {
			return true
		}
		for _, model := range provider.Models {
			if model.API == piagent.APIOpenAICodexResponses {
				return true
			}
		}
		return false
	}
	return false
}

func codexProviderModels() []piagent.Model {
	extended := map[string]*string{
		"xhigh":   stringPointer("xhigh"),
		"max":     stringPointer("max"),
		"minimal": stringPointer("low"),
	}
	standard := map[string]*string{
		"xhigh":   stringPointer("xhigh"),
		"minimal": stringPointer("low"),
	}
	return []piagent.Model{
		codexModel("gpt-5.6-terra", "GPT-5.6 Terra", extended),
		codexModel("gpt-5.6-sol", "GPT-5.6 Sol", extended),
		codexModel("gpt-5.6-luna", "GPT-5.6 Luna", extended),
		codexModel("gpt-5.5", "GPT-5.5", standard),
		codexModel("gpt-5.4-mini", "GPT-5.4 mini", standard),
	}
}

func codexModel(id, name string, thinkingLevelMap map[string]*string) piagent.Model {
	return piagent.Model{
		ID:                   id,
		Name:                 name,
		API:                  piagent.APIOpenAICodexResponses,
		Reasoning:            true,
		DefaultThinkingLevel: "medium",
		ThinkingLevelMap:     thinkingLevelMap,
		Input:                []string{"text", "image"},
		ContextWindow:        272000,
		MaxTokens:            128000,
		Capabilities:         piagent.Capabilities{ToolCall: piagent.Bool(true)},
	}
}

func stringPointer(value string) *string { return &value }

// removeLegacyChatGPTCredentialsFromAgents removes refresh-token copies left
// by older CodingTo versions. It delegates each provider deletion to Pi's
// locked credential store instead of editing auth.json with an unsafe RMW.
func (a *App) removeLegacyChatGPTCredentialsFromAgents() {
	marker := filepath.Join(a.store.Dir(), chatgptAuthMigrationFile)
	if _, err := os.Stat(marker); err == nil {
		return
	} else if !os.IsNotExist(err) {
		applog.Warnf("read ChatGPT shared-auth migration marker: %v", err)
		return
	}
	defaultDir, err := piagent.DefaultAgentDir()
	if err != nil {
		applog.Warnf("resolve shared Pi auth directory for legacy cleanup: %v", err)
		return
	}
	defaultDir = filepath.Clean(defaultDir)
	completed := true
	for _, agent := range a.store.Get().Agents {
		dataDir := filepath.Clean(agent.DataDir)
		if agent.DataDir == "" || strings.EqualFold(dataDir, defaultDir) {
			continue
		}
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		err := piagent.RunOpenAICodexLogout(ctx, dataDir)
		cancel()
		if err != nil {
			completed = false
			applog.Warnf("remove legacy ChatGPT credential for agent %s: %v", agent.ID, err)
		}
	}
	if !completed {
		return
	}
	if err := writePrivateFileAtomic(marker, []byte("completed\n")); err != nil {
		applog.Warnf("write ChatGPT shared-auth migration marker: %v", err)
	}
}
